### ISSUE TITLE
How to run code with an example dataset?

### ISSUE THREAD

**Issue by Hyacinth-YX** [ICT-ACL/DRONE_EBV#1]
Hi there! I am testing the performance of DRONE. But I am confused about how to use this tool. For example, now I downloaded "USA-road-d.USA.gr"  from http://www.diag.uniroma1.it/challenge9/download.shtml.  But I do not know how to preprocess this data file. The README.md file on the homepage says to use `mpirun -np processnum ./EBV_mpi -filename edge_list_file -vertices vertex_num -edges edge_num `   to get data. Is it right that I directly use "USA-road-d.USA.gr" as the filename in the parameter?

What's more, I'm also confused with the relationship between [EBV_mpi.cpp](https://github.com/ICT-ACL/DRONE_EBV/blob/main/EBV_mpi.cpp) and [DRONE](https://github.com/ICT-ACL/DRONE_EBV/tree/main/DRONE).  It looks like the `DRONE` start a backend service supporting graph work. And `EBV_mpi` use a c++ script to run a job on that backend? Am I right?

Looking forward to your reply!

Best regards.

**Comment by zpltys** [comment]
1. For running the EBV_mpi, you should transform the graph data into edge_list format. (each edge is one line, <src vertex id, dst vertex id>, with vertex id start from 0).
For example:
0 1
1 2
2 3
3 1
4 5

2.EBV_mpi.cpp is a graph partition job, it reads the graph data(in the edge list format) and outputs a list of files.
DRONE reads these files generated and executes the graph algorithm jobs.
